### ISSUE TITLE
Install problem — undefined: os.LookupEnv

### ISSUE THREAD

**Issue by flamsmark** [nishanths/license#1]
```
$  go get github.com/nishanths/license
# github.com/nishanths/license/base
projects/golang/src/github.com/nishanths/license/base/config.go:24: undefined: os.LookupEnv
```

Running Debian Jessie with golang package version 2:1.3.3-1.

**Comment by nishanths** [comment]
Thanks!

I've changed `os.LookupEnv` to `os.Getenv`. Previously, this might have caused an issue because `os.LookupEnv` was introduced only in [go1.5](https://golang.org/doc/go1.5).

Please try reinstalling with `go get github.com/nishanths/license`.
