### ISSUE TITLE
consider markdown licenses

### ISSUE THREAD

**Issue by derhuerst** [nishanths/license#10]
As [Markdown](https://daringfireball.net/projects/markdown/) gives text-level semantics while being very subtle, it would be [useful for licenses](https://github.com/IQAndreas/markdown-licenses).

**Comment by nishanths** [comment]
@derhuerst Thanks for the link! An optional `--markdown` flag to output licenses in Markdown is a good idea.

**Comment by scottjbarr** [comment]
Nice idea, but in the few examples I've looked at it the output still works well if you treat the output as markdown. For example, output to LICENSE.md. It renders fine as is.

**Comment by nishanths** [comment]
Thanks for the comments. Based on the fact that GitHub does not recognize Markdown formatted licenses, it doesn't seem like a good idea for Markdown-formatted licenses to be the default output format. 

I'll close this since the issue has not been active for a while.
