### ISSUE TITLE
Position of the arguments can cause app to ignore arguments

### ISSUE THREAD

**Issue by leighmcculloch** [nishanths/license#16]
Summary
===
Position of the arguments can cause app to ignore arguments. If the arguments `-o LICENSE` are placed after the license name then they are ignored.

What I expected to happen
===
I expected the following command when executed would output the license into the file `LICENSE`.

```
license mit -o LICENSE
```

What happened
===
The license was outputted to stdout and the `LICENSE` file was not written.

**Comment by leighmcculloch** [comment]
@nishanths: I'm happy to work on a change to change the behavior to what I expected above, if you're 👍 .

**Comment by nishanths** [comment]
yes, thank you! much appreciated.

**Comment by leighmcculloch** [comment]
Turns out this is the expected behavior with the Go flag library, so is behaving as expected.
