### ISSUE TITLE
Problem with separate partitions

### ISSUE THREAD

**Issue by jD91mZM2** [nishanths/license#20]
When having /home and /tmp on separate partitions, I get:
```
rename /tmp/license-388690913 /home/jD91mZM2/.license: invalid cross-device link
```

This is because you can't rename across partitions. When renaming fails with this error you should fallback to copying and deleting the original.

**Comment by nishanths** [comment]
Thanks for reporting. This should no longer be an issue, because the program no longer renames or moves these directories.

**Comment by nishanths** [comment]
I appreciate the tip about copying and deleting the original for the future.
