### ISSUE TITLE
[suggestion] Free Art License

### ISSUE THREAD

**Issue by xuv** [nishanths/license#3]
Please add the [Free Art License 1.3](http://artlibre.org/licence/lal/en/).

**Comment by nishanths** [comment]
Thanks. It would definitely be a good idea to setup an additional resource to fetch licenses that aren't available on GitHub.

**Comment by nishanths** [comment]
This is now done. :)
Running the following should print the Free Art License 1.3 in the latest release:

```
$ license free-art-1.3
```
