### ISSUE TITLE
Invalid Cross-Device Link

### ISSUE THREAD

**Issue by naftulikay** [nishanths/license#33]
I'm on Linux kernel 5.4, running elementary OS 5.0, which is Ubuntu 18.04, amd64 architecture.

When I run the CLI, I get the following error:

```
$ license -o LICENSE-APACHE apache2
rename /tmp/license-247108171 /home/naftuli/.license: invalid cross-device link
```

`/home/` and `/tmp/` live on different filesystems. I assume that this issue is caused by trying to hard-link rather than by trying to create a new file and write data to it.

**Comment by nishanths** [comment]
Thanks for the report. 

Could you try the latest version? I believe it shouldn't have this issue. With Go 1.16 or higher, you can install the latest version by running:

```
go install github.com/nishanths/license/v5@latest
```

**Comment by nishanths** [comment]
As a side note, I'll update the `README` with these newer install instructions.

**Comment by naftulikay** [comment]
Thanks, that works!
