### ISSUE TITLE
Revise GitHub Pages with newer install command

### ISSUE THREAD

**Issue by Montandalar** [nishanths/license#39]
Installed through `go install` on Debian Bookworm (testing) (go 1.17) and added `~/go/bin` to my `PATH` via `.bashrc` since this is my first time using the `go install` system. When I tried to run it I got the following error:

```
$ license gpl-3.0 -o LICENCE.txt
rename /tmp/license-349994170 /home/[REDACTED]/.license: invalid cross-device link
```

The directory ~/.license doesn't exist, which seems like it may be an installation problem. If so, I may need a bit of help with installation instructions. If not, my system is partitioned with separate partitions for `/` and `/home`, so my guess is this may be the cause of the issue; that or problems with the `/tmp` filesystem which resides in memory.

**Comment by nishanths** [comment]
Thanks for the report. I believe this was an issue in an older version of the program (the program was renaming files, which didn’t work across partitions). Please see this related issue for a fix: https://github.com/nishanths/license/issues/33.

**Comment by Montandalar** [comment]
Thank you, I can confirm that installing with the correct incantation worked for me. What I recommend you do is update the [GitHub Pages Site](https://nishanths.github.io/license/) which is where I landed from an internet search and why I got the install command wrong in the first place. That will hopefully prevent anyone else from making the same mistake.

**Comment by nishanths** [comment]
I'd forgotten about the install command on the website.  I'll make the change.
