### ISSUE TITLE
Clone in Python please?

### ISSUE THREAD

**Issue by Naereen** [nishanths/license#4]
Could you try to write a clone of your great project in Python please?

**Comment by nishanths** [comment]
[licen](https://pypi.python.org/pypi/licen) showed up after running a few searches on Google and PyPI, in case it helps.

If you are unable to install `license` using `homebrew`or `go`, you can [get the binary file](https://github.com/nishanths/license/wiki/Install-binaries).

**Comment by Naereen** [comment]
Indeed [licen](http://github.com/lord63/licen) ([also on pypi](https://pypi.python.org/pypi/licen)) or [lice](https://github.com/licenses/lice) both seems to be good, sorry I should have searched myself before asking.
And you are also right, thanks, installing the binary as you explained works fine (although 8.4 M for a small script like this is the reason why I am going to use [licen](http://github.com/lord63/licen)).

**Comment by nishanths** [comment]
:+1:

**Comment by nishanths** [comment]
If you're interested in following the Go issue with growing binary sizes, check these out! 
- https://github.com/golang/go/issues/6853
- https://donatstudios.com/Golang-Binary-Sizes
