### ISSUE TITLE
Can't add name to Apache license

### ISSUE THREAD

**Issue by dinhanhx** [nishanths/license#48]
When I run `license -name dinhanhx -o LICENSE apache-2.0`, the LICENSE file doesn't get year and name updated. 

I just build it from source at this commit 7234d012dc83008648a2b136d59b438091af899b

**Comment by nishanths** [comment]
Thank you for the report. Please see these two comments: https://github.com/nishanths/license/issues/36#issuecomment-958912194 and https://github.com/nishanths/license/issues/18#issuecomment-336199974.

I'm closing this issue for now, but please feel free to reopen it.
